### ISSUE TITLE
Cutout Ring's color inverted when Force Dark enabled

### ISSUE THREAD

**Issue by someone5678** [ArrowOS-Devices/android_device_xiaomi_sweet#2]
If force dark is enabled in dev settings, cutout ring's color inverts to white.
It makes white blur around pictures when using front camera.

Screenshot: https://imgur.com/a/8wfu69V

Test: Taken picture with front camera using Gcam Go with force dark setting enabled

**Comment by danielml3** [comment]
Fixed with https://github.com/ArrowOS-Devices/android_device_xiaomi_sweet/commit/6d0ad137dc0348ba769a0e44c8345dfbb8027827
