### ISSUE TITLE
Selinux neverallows are ignored

### ISSUE THREAD

**Issue by brvn0** [ArrowOS-Devices/android_device_xiaomi_sweet#4]
Hey I fixed the neverallows and therefore made user builds possible, if you want check this [commit](https://github.com/devices-ng/android_device_xiaomi_sweet/commit/2e5a9fe8ebbd40bd864d47c967a1b7e0279c368e) and eventually cherry-pick it
The changes are tested by myself but I encourage you to test it on your own 

I would be happy if u accept this change bc u did a lot of work to bringup the tree and I wanted to give something back :D

**Comment by danielml3** [comment]
Hello, thanks for the contribution! I'll take a look at it later and pick it :)

**Comment by brvn0** [comment]
Because the commit is in the tree now ig the issue can be closed
